apiVersion: v1
kind: Service
metadata:
  name: zwitscher-service
  labels:
    zwitscher: service
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8080
  selector:
    zwitscher: service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwitscher-service
  labels:
    zwitscher: service
    cloudcontrol.enabled: "true"
    cloudcontrol.index: "4"
    LAUNCHPAD_ENABLE: "true"
    LAUNCHPAD_COLOR: LIGHT_GREEN
    LAUNCHPAD_ROW: "1"
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 1
  template:
    metadata:
      labels:
        zwitscher: service
    spec:
      containers:
      - name: zwitscher-service
        image: "zwitscher-service:1.1.1"
        #imagePullPolicy: Always
        resources:
          requests:
            memory: "196Mi"
            cpu: "250m"
          limits:
            memory: "324Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8080
          timeoutSeconds: 30
        env:
        - name: CONSUL_HOST
          value: zwitscher-consul
        - name: TWITTER_APP_ID
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: api-key
        - name: TWITTER_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: api-secret

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    zwitscher: service
  name: zwitscher-service
  namespace: default
spec:
  backend:
    serviceName: zwitscher-service
    servicePort: 8080
