apiVersion: v1
kind: Service
metadata:
  name: zwitscher-board
  labels:
    zwitscher: board
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8081
  selector:
    zwitscher: board
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwitscher-board
  labels:
    zwitscher: board
    cloudcontrol.enabled: "true"
    cloudcontrol.index: "5"
    LAUNCHPAD_ENABLE: "true"
    LAUNCHPAD_COLOR: LIGHT_BLUE
    LAUNCHPAD_ROW: "2"
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 1
  template:
    metadata:
      labels:
        zwitscher: board
    spec:
      containers:
      - name: zwitscher-board
        image: "zwitscher-board:1.0.1"
        #imagePullPolicy: Always
        resources:
          requests:
            memory: "196Mi"
            cpu: "250m"
          limits:
            memory: "324Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8081
          initialDelaySeconds: 90
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8081
          timeoutSeconds: 30
        env:
        - name: CONSUL_HOST
          value: zwitscher-consul
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    zwitscher: board
  name: zwitscher-board
  namespace: default
spec:
  backend:
    serviceName: zwitscher-board
    servicePort: 8081
